# Generated by Django 3.2.7 on 2021-09-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bill',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='earning_session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('basic', 'basic'), ('gold', 'gold'), ('platnum', 'platnum'), ('vip', 'vip')], max_length=8),
        ),
    ]
