# Generated by Django 3.2.7 on 2021-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210906_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic', 'basic'), ('gold', 'gold'), ('platnum', 'platnum'), ('vip', 'vip')], max_length=8, null=True),
        ),
    ]
